#!/bin/bash
#PBS -N ams500m01b
#PBS -q long
#PBS -W group_list=s2393
#PBS -l select=27:ncpus=20:model=ivy
#PBS -l walltime=48:00:00
#PBS -j oe
#PBS -m abe
#PBS -l site=needed=/home1+/home3+/home4+/nobackupp17

module load comp-intel/2020.4.304
module load mpi-hpe/mpt.2.28_25Apr23_rhel87
module load szip/2.1.1
module load hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt

export RUN_DIR=/nobackupp11/mpoinell/thwaites_500m/run_ams500m01b/

cd $RUN_DIR
mpiexec -np 540 ./mitgcmuv
